title: Marcelo Miranda de Oliveira
#logo: assests/personal_foto.png
description: PhD Material Engineering| Physicist | Data Scientist
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect
