title: Marcelo Miranda de Oliveira
#logo: link para imagem que será utilizada
description: PhD Material Scientist | Data Scientist | Physicist
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal
